dist: bionic
language: java
sudo: false
install: true

jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
  - oraclejdk9
  - oraclejdk11
  - oraclejdk12
  - oraclejdk13
  - oraclejdk14

addons:
 apt:
  packages:
   - openjdk-8-jdk

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: true
